/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/IS2GGOBsY8s
 */
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import ChatComponent from '@/components/chat-component';
export default function ChatPage() {
	return (
			<ChatComponent/>
	);
}
