/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Jnr7xQW6RIA
 */
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function LoginPage() {
  return (
    <div className="flex min-h-screen items-center justify-center bg-gray-100">
      <div className="w-full max-w-md p-8 space-y-6 bg-white rounded-lg shadow">
        <div className="flex justify-center">
          <FlagIcon className="h-8 w-8 text-black" />
        </div>
        <h1 className="text-center text-3xl font-bold">Sign in to Ollama Web UI</h1>
        <form className="space-y-6">
          <div>
            <label className="block text-sm font-medium text-gray-700" htmlFor="email">
              Email
            </label>
            <Input
              className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
              id="email"
              placeholder="Enter Your Email"
              type="email"
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700" htmlFor="password">
              Password
            </label>
            <Input
              className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
              id="password"
              placeholder="Enter Your Password"
              type="password"
            />
          </div>
          <div>
            <Button className="w-full">Sign In</Button>
          </div>
        </form>
        <div className="text-center">
          <p className="text-sm">
            Don't have an account?
            <Link className="font-medium text-indigo-600 hover:text-indigo-500" href="#">
              Sign up
            </Link>
          </p>
        </div>
      </div>
    </div>
  )
}


function FlagIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
      <line x1="4" x2="4" y1="22" y2="15" />
    </svg>
  )
}
